apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homelab-pg
  namespace: database
spec:
  instances: 1

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"

  postgresql:
    parameters:
      shared_buffers: "128MB"
      max_connections: "100"
      work_mem: "4MB"
      maintenance_work_mem: "64MB"

  storage:
    size: 20Gi
